In [1]:
import numpy as np
import pandas as pd

In [6]:
initial = 1000000
rate = 0.08
mu = 0.1
sigma = 0.4
prop = 0.4
draw = 100000
N = 10
M = 1000

In [8]:
W = np.zeros(N+1)
W

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
W[0] = initial
W

array([1000000.,       0.,       0.,       0.,       0.,       0.,
             0.,       0.,       0.,       0.,       0.])

In [20]:
np.random.seed(0)

for i in range(N):
    S = prop * W[i]
    D = W[i] - S
    e = np.random.randn()
    R = np.exp((mu-0.5*sigma**2) + sigma * e)
    W1 = S * R + D * (1 + rate)
    W2 = W1 - draw
    W[i+1] = W2    
W    

array([1000000.        , 1374405.42755652, 1448840.92395795,
       1713411.29053   , 2723815.83435043, 4011160.50101622,
       3606481.17815611, 4389170.99522042, 4430094.95837095,
       4505415.85953489, 4986260.59790667])

In [23]:
success = 0
np.random.seed(0)

for j in range(M):
    for i in range(N):
        S = prop * W[i]
        D = W[i] - S
        e = np.random.randn()
        R = np.exp((mu-0.5*sigma**2) + sigma * e)
        W1 = S * R + D * (1 + rate)
        W2 = W1 - draw
        W[i+1] = W2
    if W[N] > 0:
        success = success + 1
success

883

In [36]:
def PositiveWealth(initial, rate, mu, sigma, prop, draw, N, M):
    W = np.zeros(N+1)
    W[0] = initial
    
    success = 0
    np.random.seed(0)

    for j in range(M):
        for i in range(N):
            S = prop * W[i]
            D = W[i] - S
            e = np.random.randn()
            R = np.exp((mu-0.5*sigma**2) + sigma * e)
            W1 = S * R + D * (1 + rate)
            W2 = W1 - draw
            W[i+1] = W2
        if W[N] > 0:
            success = success + 1
    return success/M    

In [37]:
initial = 1000000
rate = 0.08
mu = 0.1
sigma = 0.4
prop = 0.4
draw = 100000
N = 10
M = 1000

PositiveWealth(initial, rate, mu, sigma, prop, draw, N, M)

0.883

In [40]:
np.mean(W), np.std(W)

(994441.3610514565, 155434.24346259222)

In [44]:
def WealthWithCushion(initial, rate, mu, sigma, prop, draw, N, M, cushion):
    W = np.zeros(N+1)
    W[0] = initial
    
    W3 = np.zeros(M)
    np.random.seed(0)

    for j in range(M):
        for i in range(N):
            S = prop * W[i]
            D = W[i] - S
            e = np.random.randn()
            R = np.exp((mu-0.5*sigma**2) + sigma * e)
            W1 = S * R + D * np.exp(rate)
            if W1 > cushion * draw:
                drawdown = draw
            else:
                drawdown = W1 / cushion
            W2 = W1 - drawdown
            W[i+1] = W2
        W3[j] = W[N]        
    return (np.mean(W3), np.std(W3))    

In [45]:
initial = 1000000
rate = 0.08
mu = 0.1
sigma = 0.4
prop = 0.4
draw = 100000
N = 10
M = 1000
cushion = 3

WealthWithCushion(initial, rate, mu, sigma, prop, draw, N, M, cushion)

(827856.9187569012, 830144.7983431504)