# numpy
#### Numerical Python

#### 벡터 및 행렬 연산에 편리한 기능 제공

In [1]:
import numpy as np

In [7]:
a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(len(a))

<class 'numpy.ndarray'>
(3,)
3


In [8]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(type(b))
print(b.shape)
print(len(b))

<class 'numpy.ndarray'>
(2, 3)
2


### Attributes of array

In [13]:
print(a.ndim)
print(a.size)
print(a.dtype)
print(a.itemsize)
print()
print(b.ndim)
print(b.size)
print(b.dtype)
print(b.itemsize) # int 4byte

1
3
int32
4

2
6
int32
4


### Array creation

In [30]:
print(np.zeros(3))
print()
print(np.zeros((3,4)))
print()
print(np.ones(3))
print()
print(np.ones((3,4)))
print()
print(np.identity(5)) 
print()
print(np.arange(6)) 
print()
print(np.arange(6.0))
print()
print(np.arange(2, 20, 3)) 
print()
print(np.linspace(2, 3, 11)) 
print()
print(np.arange(12).reshape(3, 4))
print()
print(np.arange(12).reshape(-1, 3))

[0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[0 1 2 3 4 5]

[0. 1. 2. 3. 4. 5.]

[ 2  5  8 11 14 17]

[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3. ]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### Basic operations

In [36]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(a) 
print(b)
print('---------------')
print(a-b)
print(a+3)
print(np.array([1,2,3]) + 3) # [1,2,3] + 3 error
print(np.array([1, 2, 3]) / np.array([4, 5, 6])) # [1,2,3] / [4,5,6] error
print(b**2)
print(a < 35)

[20 30 40 50]
[0 1 2 3]
---------------
[20 29 38 47]
[23 33 43 53]
[4 5 6]
[0.25 0.4  0.5 ]
[0 1 4 9]
[ True  True False False]


In [50]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])
print(A) 
print(B)
print(A*B)
print(A@B)
print(A.dot(B))
print()
print('Linear algebra')
from numpy.linalg import inv
print (inv(A)) # inverse of a matrix.
print (A @ inv(A))
print(A.T) # np.transpose(A)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]

Linear algebra
[[ 1. -1.]
 [ 0.  1.]]
[[1. 0.]
 [0. 1.]]
[[1 0]
 [1 1]]


### np.sum(), np.mean(), np.max(), np.argmax()

In [55]:
B = np.arange(12).reshape(3, 4)
print(B)
print(np.sum(B))
print(np.sum(B, axis=0))
print(np.sum(B, axis=1))
print(np.mean(B))
print(np.mean(B, axis=0))
print(np.max(B))
print(np.argmax(B))
B = 2 * B
print(B)
print(np.max(B))
print(np.argmax(B)) # return index
print(np.argmax(B, axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[ 6 22 38]
5.5
[4. 5. 6. 7.]
11
11
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
22
11
[2 2 2 2]


### np.hstack, np.vstack, np.hsplit

In [59]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a)
print(b)
print(np.hstack((a,b)))
print(np.vstack((a,b)))
x = np.arange(24).reshape(3, 8)
print(x)
print()
print(np.hsplit(x,2))
print()
print(np.hsplit(x,4))


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]

[array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]]), array([[ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])]

[array([[ 0,  1],
       [ 8,  9],
       [16, 17]]), array([[ 2,  3],
       [10, 11],
       [18, 19]]), array([[ 4,  5],
       [12, 13],
       [20, 21]]), array([[ 6,  7],
       [14, 15],
       [22, 23]])]


In [67]:
print(np.hsplit(x, np.array([2])))
print()
print(np.hsplit(x, np.array([3, 6])))
print()
print(np.hsplit(x, np.array([2, 5, 7])))
print()
x = np.arange(24).reshape(8, 3)
print(x)
print()
print(np.vsplit(x, 2))
print()
print(np.vsplit(x, 4))
print()
print(np.vsplit(x, np.array([2, 7])))

[array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13],
       [15, 16],
       [18, 19],
       [21, 22]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17],
       [20],
       [23]])]

[array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]]), array([], shape=(8, 0), dtype=int32), array([], shape=(8, 0), dtype=int32)]

[array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13],
       [15, 16],
       [18, 19],
       [21, 22]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17],
       [20],
       [23]]), array([], shape=(8, 0), dtype=int32), array([], shape=(8, 0), dtype=int32)]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

[array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]]),